BLACKLIST:
  word: ['是', '我']
  pos: ['u*', 'x', 'y', 'z', 's', 'r*', 'q', 'p', 'o', 'k', 'h', 'd', 'c']
WORD_LENGTH:
  min_len: 2
  max_len: 5

VALIDATION:
  doc_freq_threshold: 3
  term_freq_threshold: 8

OUTPUT_FILE_PATH:
  char_freq: './output/char_freq.csv'
  scan_result: './output/scan_result.csv'
  ngrams: './output/ngrams.csv'
  merged_ngrams: './output/merged_ngrams.csv'
  entropy_result: './output/entropy_result.csv'
  mi_result: './output/mi_result.csv'
  final_result: './output/final_result.csv'
INPUT_FILE_PATH:
  input_file: './input/random_user_20W_0829.csv'
