BLACKLIST:
  word: ['是', '我']
  pos: ['u*', 'x', 'y', 'z', 's', 'r*', 'q', 'p', 'o', 'k', 'h', 'd', 'c']
WORD_LENGTH:
  min_len: 2
  max_len: 5

VALIDATION:
  doc_freq_threshold: 3
  term_freq_threshold: 8

FILENAME:
  input_file: input/random_user_20W_0829.csv
  scan_result : output/scan_result.csv