BLACKLIST:
  ['的', '一', '了', '是', '我', '不', '在', '人', '们', '有', '来', '他', '这', '上', '着', '个', '到', '大', '里', '说', '就', '去', '子', '得', '也', '和', '那', '要', '下', '看', '时', '过', '出', '小', '么', '起', '你', '都', '把', '好', '还', '多', '没', '为', '又', '可', '学', '只', '以', '会', '样', '年', '想', '能', '同', '老', '中', '十', '从', '自', '前', '它', '后', '然', '走', '很', '像', '见', '两', '用', '她', '国', '动', '进', '成', '回', '什', '边', '作', '对', '开', '而', '己', '些', '现', '候', '向','给','才','与']
WORD_LENGTH:
  min_len: 2
  max_len: 5

VALIDATION:
  doc_freq_threshold: 3
  term_freq_threshold: 8